version: 2.1

jobs:
  test:
    docker:
    - image: cimg/base:2023.03
    steps:
    - checkout
    - run: echo "this is the test job"
    - run: sleep 300

workflows:
  test:
    jobs:
      - test
